---
- hosts: ansible
  tasks:
  - name: create docker image
    command: docker build -t devopst/regapp:latest .
    args:
      chdir: /opt/docker
  - name: push docker image
    command: docker push devopst/regapp:latest