---
- hosts: k8s
  tasks:
  - name: deploy regapp on k8s
    command: kubectl apply -f /opt/docker/regapp-deploy.yml
  - name: create service for regapp
    command: kubectl apply -f /opt/docker/regapp-service.yml